bankingsystem/urls.py
from django.conf import settings
from django.urls import re_path as url, include
from django.conf.urls.static import static
from django.contrib import admin

from accounts.views import (login_view,
                            register_view,
                            logout_view
                            )

from core.views import home, about, contact


urlpatterns = [
    # admin
    url(r'^admin/', admin.site.urls),
    # Accounts
    url(r'^login/$', login_view, name='login'),
    url(r'^register/$', register_view, name='register'),
    url(r'^logout/$', logout_view, name='logout'),
    # core
    url(r'^$', home, name='home'),
    url(r'^#contact$', contact, name='contact'),
    url(r'^about/$', about, name='about'),

    # transactions
    url(r'^', include('transactions.urls', namespace='transactions')),
]

transactions/urls.py
from django.urls import re_path as url

from .views import diposit_view, withdrawal_view
app_name='transactions'
urlpatterns = [
    # url(r'^$', home_view, name='home'),
    url(r'^deposit/$', diposit_view, name='deposit'),
    url(r'^withdrawal/$', withdrawal_view, name='withdrawal'),
]

core/models.py
from django.db import models

# Create your models here.


class Contact(models.Model):
    name = models.CharField(max_length=130, blank=False)
    email = models.EmailField(blank=False, null=True, max_length=130)
    message = models.CharField(max_length=830)

    def __str__(self):
        return self.name

core/forms.py
from django import forms

from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ["name", "email", "message"]

core/views.py
from django.db.models import Sum
from django.shortcuts import render,redirect
from django.contrib import messages

from transactions.models import Diposit, Withdrawal, Interest
from .forms import ContactForm
from .models import Contact


def home(request):
    if not request.user.is_authenticated:
        return render(request, "core/home.html", {})
    else:
        user = request.user
        deposit = Diposit.objects.filter(user=user)
        deposit_sum = deposit.aggregate(Sum('amount'))['amount__sum']
        withdrawal = Withdrawal.objects.filter(user=user)
        withdrawal_sum = withdrawal.aggregate(Sum('amount'))['amount__sum']
        interest = Interest.objects.filter(user=user)
        interest_sum = interest.aggregate(Sum('amount'))['amount__sum']

        context = {
                    "user": user,
                    "deposit": deposit,
                    "deposit_sum": deposit_sum,
                    "withdrawal": withdrawal,
                    "withdrawal_sum": withdrawal_sum,
                    "interest": interest,
                    "interest_sum": interest_sum,
                  }

        return render(request, "core/transactions.html", context)


def about(request):
    return render(request, "core/about.html", {})


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST or None)
        if form.is_valid():
            save_it = form.save(commit=False)
            save_it.save()
            messages.success(request, 'Thanks, Engr.ANTHONY will get in touch')
            return render(request, 'core/home.html', {'form': form})

        else:
            messages.error(request, 'Ensure all fields are entered correctly')

        return render(request, 'core/home.html', {'form': form})

core/templates/core/about.html
{% extends 'core/base.html' %}

{% block title %} About | {{ block.super }}{% endblock title %}

{% block content %}
<div class="container">
<h1>About The Developer</h1>

<hr>
<p>Anthony is a professional software developer with over 6years of active web development using the python programming language. He has successfully deployed several python projects written in Django, Flask, FASTAPI ETC.. He has also worked as a  professional software data scientist and has employed several ML models in analysing dataset.</p>

<p>As an engineering graduate with a strong flair for mathematical analysis, Anthony has built several complex analytical software, and has mentored several young software developers in their early phase of their career.</p>


<p> This website is deployed for illustrative purpose, the actual job with all functionality was done for a client and this representation only shows the little of what can be achieved using Python django, js and bootstrap.Please feel free to use the contact form in the contact page</p>
</div>

{% endblock content %}

core/templates/core/base.html
 <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <!--
    Awesome Template
    http://www.templatemo.com/preview/templatemo_450_awesome
    -->
    <title>TYBANK</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% load static %}

    <link rel="stylesheet"  href='{% static "css/animate.min.css" %}'>
    <link rel="stylesheet"  href='{% static "css/bootstrap.min.css" %}'>
    <link rel="stylesheet"   href='{% static "css/font-awesome.min.css" %}'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href='{% static "css/templatemo-style.css" %}'>
    <script src='{% static "js/jquery.js" %}'></script>
    <script src='{% static "js/bootstrap.min.js" %}'></script>
    <script src='{% static "js/jquery.singlePageNav.min.js" %}'></script>
    <script src="static/js/typed.js"></script>
    <script src='{% static "js/wow.min.js" %}'></script>
    <script src='{% static "js/custom.js" %}'></script>


  </head>

  <body>



    {% block content %}

    {% endblock content %}
  </body>
<body>
<div>
{% include "core/footer.html" %}
</div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins)
        <script type="text/javascript" src="{% static 'js/jquery.min.js' %}" ></script>
        <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}" ></script>-->
  </body>
</html>

core/templates/core/contact.html
{% csrf_token %}
<section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2 class="wow bounceIn" data-wow-offset="50" data-wow-delay="0.3s">CONTACT <span>DEVELOPER</span></h2>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-12 wow fadeInLeft" data-wow-offset="50" data-wow-delay="0.9s">
                <form action="#" method="post">
                    {% csrf_token %}
                   {{ form }}
                    <label>NAME</label>
                    <input name="name" type="text" class="form-control" id="fullname">

                    <label>EMAIL</label>
                    <input name="email" type="email" class="form-control" id="email">

                    <label>MESSAGE</label>
                    <textarea name="message" rows="4" class="form-control" id="message"></textarea>

                    <input type="submit" class="form-control">
                </form>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-12 wow fadeInRight" data-wow-offset="50" data-wow-delay="0.6s">
                <address>
                    <p class="address-title">OUR ADDRESS</p>
                    <span>Anthony's Estate, Lagos, Nigeria</span>
                    <span>Michael Udoh Estate, Lagos, Nigeria</span>
                    <p><i class="fa fa-phone"></i> 08100725049</p>
                    <p><i class="fa fa-envelope-o"></i> buksbam@gmail.com</p>
                    <p><i class="fa fa-map-marker"></i>  Anthony's Estate, Lagos, Nigeria</p>
                </address>
                <ul class="social-icon">
                    <li><h4>WE ARE SOCIAL</h4></li>
                    <li><a href="#" class="fa fa-facebook"></a></li>
                    <li><a href="#" class="fa fa-twitter"></a></li>
                    <li><a href="#" class="fa fa-instagram"></a></li>
                </ul>
            </div>
        </div>
    </div>
</section>
<!-- end contact -->

core/templates/core/footer.html
<hr>
<footer class="footer navbar-fixed">
    <!--Footer Links-->
    <div class="container-fluid">
        <div class="row">
            <!--First column-->
            <div class="col-md-6">
                <h4 class="title"><b>The developer</b></h4>

                <p>Contact Anthony the developer for your personalized python projects including DATA SCIENCE tasks ML and AI.</p>

                </div>
            <!--/.First column-->
            <!--Second column-->
            <div class="col-md-6">
                <h5 class="title"><b>Links</b></h5>

                <a href="{% url 'home' %}">Home </a>|
                <a href="{% url 'about' %}">About Us</a> |&nbsp;
                <!-- start copyright -->

                <!-- end copyright -->


            </div>
            <!--/.Second column-->
        </div>
    </div>
    <footer id="copyright">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    <p class="wow bounceIn" data-wow-offset="50" data-wow-delay="0.3s">
                        Copyright &copy; 2022 Tonymaths</p>
                </div>
            </div>
        </div>
    </footer>
</footer>
<br>

core/templates/core/home.html
{% extends 'core/base.html' %}


{% block title %} {{ block.super }}{% endblock title %}

{% block content %}
{% include "core/layout.html" %}
<!-- start home -->
<section id="home">
    <div class="container">
        <div class="row">
            <div class="col-md-offset-2 col-md-8">
                <h1 class="wow fadeIn" data-wow-offset="50" data-wow-delay="0.9s">A banking System with a <span>difference</span></h1>
                <div class="element">
                    <div class="sub-element">Hello, welcome to TYbank</div>
                    <div class="sub-element">A secured banking system developed by Anthony C.E, a Python Software developer</div>
                    <div class="sub-element">Tybank is an online banking system with services to meet your needs</div>
                    <div class="sub-element">Tybank system contains highly secured features from the latest version of django python Framework</div>
                </div>
                <a data-scroll href="{% url 'register' %}" class="btn btn-default wow fadeInUp" data-wow-offset="50" data-wow-delay="0.6s">GET STARTED</a>
                <a class="btn btn-primary btn-md" href="{% url 'login' %}" role="button">Load Account Details</a>
            </div>
        </div>
    </div>
</section>
<!-- end home -->

<!-- start about -->
<section id="about">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2 class="wow bounceIn" data-wow-offset="50" data-wow-delay="0.3s">WE ARE <span>TYBANK</span></h2>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-12 wow fadeInLeft" data-wow-offset="50" data-wow-delay="0.6s">
                <div class="media">
                    <div class="media-heading-wrapper">
                        <div class="media-object pull-left">
                            <i class="fa fa-mobile"></i>
                        </div>
                        <h3 class="media-heading">A RELIABLE BANK SYSTEM</h3>
                    </div>
                    <div class="media-body">
                        <p>Tybank system contains highly secured features from the latest version of django python library,with  a reliable structure to meet your needs <a rel="nofollow" href="#team" target="_parent">designed by Anthony</a>
                    </div>
                </div>
            </div>

            <div class="col-md-4 col-sm-4 col-xs-12 wow fadeInRight" data-wow-offset="50" data-wow-delay="0.6s">
                <div class="media">
                    <div class="media-heading-wrapper">
                        <div class="media-object pull-left">
                            <i class="fa fa-html5"></i>
                        </div>
                        <h3 class="media-heading">Features</h3>
                    </div>
                    <div class="media-body">
                        <p>A functional banking system designed to specially met your banking needs with features including but not limited to</p>

                        <ul >
                            <li> a secured and friendly<a href="#top"> deposit</a>system</li>
                            <li>A controlled<a href="#about">withdrawal</a> system</li>
                            <li>Special <a href="#team">savings</a> account features</li>
                            <li>Special <a href="#team">current</a> account features</li>
                            <li> A celery based interest count logic</li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-12 wow fadeInUp" data-wow-offset="50" data-wow-delay="0.9s">
                <div class="media">
                    <div class="media-heading-wrapper">
                        <div class="media-object pull-left">
                            <i class="fa fa-comment-o"></i>
                        </div>
                        <h3 class="media-heading">FREE SUPPORT</h3>
                    </div>
                    <div class="media-body">
                        <p>Credits goes to <a rel="nofollow" href="#team">Awesome designers</a> for front end design hint  and <a rel="nofollow" href="/">Github</a>  for further hints and version saves.i hope this demo system will build your confidence in my design abilities.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>
<!-- end about -->

<!-- start team -->
<section id="team">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2 class="wow bounceIn" data-wow-offset="50" data-wow-delay="0.3s"><span>TYBANK KEY</span> TEAM</h2>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12 wow fadeIn" data-wow-offset="50" data-wow-delay="1.3s">
                <div class="team-wrapper">
                    <img src="static/images/team-img1.jpg" class="img-responsive" alt="team img 1">
                    <div class="team-des">
                        <h4>AWESOME TEAM</h4>
                        <span>Partners</span>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elitquisque tempus ac eget diam et laoreet phasellus ut nisi id leo molest.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12 wow fadeIn" data-wow-offset="50" data-wow-delay="1.6s">
                <div class="team-wrapper">
                    <img src="static/images/team-img2.jpg" class="img-responsive" alt="team img 2">
                    <div class="team-des">
                        <h4>ANTHONY</h4>
                        <span>Developer</span>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elitquisque tempus ac eget diam et laoreet phasellus ut nisi id leo molest.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12 wow fadeIn" data-wow-offset="50" data-wow-delay="1.3s">
                <div class="team-wrapper">
                    <img src="static/images/team-img3.jpg" class="img-responsive" alt="team img 3">
                    <div class="team-des">
                        <h4>JULIA</h4>
                        <span>Director</span>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elitquisque tempus ac eget diam et laoreet phasellus ut nisi id leo molest.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12 wow fadeIn" data-wow-offset="50" data-wow-delay="1.6s">
                <div class="team-wrapper">
                    <img src="static/images/team-img4.jpg" class="img-responsive" alt="team img 4">
                    <div class="team-des">
                        <h4>TYBANK</h4>
                        <span>Managers</span>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elitquisque tempus ac eget diam et laoreet phasellus ut nisi id leo molest.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- end team -->

<!-- start service -->
<section id="service">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2 class="wow bounceIn" data-wow-offset="50" data-wow-delay="0.3s">OUR <span>YET TO INCLUDE</span> FEATURES</h2>
            </div>
            <div class="col-md-4 wow fadeIn" data-wow-offset="50" data-wow-delay="0.6s">
                <i class="fa fa-laptop"></i>
                <h4>Internet banking</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elitquisque tempus ac eget diam et laoreet phasellus ut nisi id leo molestie. Adipiscing vitae vel quam proin eget mauris eget. Lorem ipsum dolor sit amet, consectetur adipiscing elitquisque tempus ac eget diam et laoreet phasellus ut nisi id leo molestie.</p>
            </div>
            <div class="col-md-4 active wow fadeIn" data-wow-offset="50" data-wow-delay="0.9s">
                <i class="fa fa-cloud"></i>
                <h4>Updated AI Computing</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elitquisque tempus ac eget diam et laoreet phasellus ut nisi id leo molestie. Adipiscing vitae vel quam proin eget mauris eget. Lorem ipsum dolor sit amet, consectetur adipiscing elitquisque tempus ac eget diam et laoreet phasellus ut nisi id leo molestie.</p>
            </div>
            <div class="col-md-4 wow fadeIn" data-wow-offset="50" data-wow-delay="0.6s">
                <i class="fa fa-cog"></i>
                <h4> Upgraded UX Design</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elitquisque tempus ac eget diam et laoreet phasellus ut nisi id leo molestie. Adipiscing vitae vel quam proin eget mauris eget. Lorem ipsum dolor sit amet, consectetur adipiscing elitquisque tempus ac eget diam et laoreet phasellus ut nisi id leo molestie.</p>
            </div>
        </div>
    </div>
</section>
<!-- end servie -->
<br>
{% include "core/contact.html" %}

{% endblock content %}

core/templates/core/layout.html
<body id="top">

<!-- start preloader -->
<div class="preloader">
    <div class="sk-spinner sk-spinner-wave">
        <div class="sk-rect1"></div>
        <div class="sk-rect2"></div>
        <div class="sk-rect3"></div>
        <div class="sk-rect4"></div>
        <div class="sk-rect5"></div>
    </div>
</div>
<!-- end preloader -->
<!-- start header -->
<header>
    <div class="container">
        <div class="row">
            <div class="col-md-3 col-sm-4 col-xs-12">
                <p><i class="fa fa-phone"></i><span> Phone</span>+234-8100725049</p>
            </div>
            <div class="col-md-3 col-sm-4 col-xs-12">
                <p><i class="fa fa-envelope-o"></i><span> Email</span><a href="#">buksbam@gmail.com</a></p>
            </div>
            <div class="col-md-5 col-sm-4 col-xs-12">
                <ul class="social-icon">
                    <li><span>Meet us on</span></li>
                    <li><a href="#" class="fa fa-facebook"></a></li>
                    <li><a href="#" class="fa fa-twitter"></a></li>
                    <li><a href="#" class="fa fa-instagram"></a></li>
                    <li><a href="#" class="fa fa-apple"></a></li>
                </ul>
            </div>
        </div>
    </div>
</header>
<!-- end header -->

<!-- start navigation -->

<nav class="navbar navbar-default templatemo-nav" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon icon-bar"></span>
                <span class="icon icon-bar"></span>
                <span class="icon icon-bar"></span>
            </button>
            <a href="#" class="navbar-brand">Tybank System</a>
        </div>
        <div class="collapse navbar-collapse">

            <ul class="nav navbar-nav navbar-right">
                <li><a href="#top">HOME</a></li>
                <li><a href="#about">ABOUT</a></li>
                <li><a href="#team">TEAM</a></li>
                <li><a href="#service">SERVICE</a></li>
                <li><a href="#contact">CONTACT</a></li>
                <!--<li>
                    <a href="/"> Home <span class="sr-only">(current)</span></a>
                </li>
                <li>
                    {% if not request.user.is_authenticated %}
                    <a href='{% url "login" %}'>Sign In</a>
                </li>
                <li >
                    <a href='{% url "register" %}'>Register</a>
                </li>
                {% else %}
                <li>
                    <a href='{% url "logout" %}'>logout</a>
                    {% endif %}
                </li>
                <li class="nav-item text-white">
                    <a class="nav-link" href="#about">About</a>
                </li>
                <li><a href="#contact">CONTACT</a></li>-->
            </ul>
        </div>
    </div>
</nav>
<!-- end navigation -->

core/templates/core/messages.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}

core/templates/core/nav.html
<body id="top">

<!-- start preloader -->
<div class="preloader">
    <div class="sk-spinner sk-spinner-wave">
        <div class="sk-rect1"></div>
        <div class="sk-rect2"></div>
        <div class="sk-rect3"></div>
        <div class="sk-rect4"></div>
        <div class="sk-rect5"></div>
    </div>
</div>
<!-- end preloader -->
<!-- start header -->
<header>
    <div class="container">
        <div class="row">
            <div class="col-md-3 col-sm-4 col-xs-12">
                <p><i class="fa fa-phone"></i><span> Phone</span>+234-8100725049</p>
            </div>
            <div class="col-md-3 col-sm-4 col-xs-12">
                <p><i class="fa fa-envelope-o"></i><span> Email</span><a href="#">anthonyezembamalu@yahoo.com</a></p>
            </div>
            <div class="col-md-5 col-sm-4 col-xs-12">
                <ul class="social-icon">
                    <li><span>Meet us on</span></li>
                    <li><a href="#" class="fa fa-facebook"></a></li>
                    <li><a href="#" class="fa fa-twitter"></a></li>
                    <li><a href="#" class="fa fa-instagram"></a></li>
                    <li><a href="#" class="fa fa-apple"></a></li>
                </ul>
            </div>
        </div>
    </div>
</header>
<!-- end header -->

<!-- start navigation -->

<nav class="navbar navbar-default templatemo-nav" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon icon-bar"></span>
                <span class="icon icon-bar"></span>
                <span class="icon icon-bar"></span>
            </button>
            <a href="#" class="navbar-brand">Tybank System</a>
        </div>
        <div class="collapse navbar-collapse">

            <ul class="nav navbar-nav navbar-right">
                <li><a href="#top">Profile</a></li>
                <li><a href="#about">Deposit(s)</a></li>
                <li><a href="#team">Withdrawal(s)</a></li>
                <li><a href="#service">Interest(s)</a></li>
                <li><a href="#contact">Contact</a></li>
                <!--<li>
                    <a href="/"> Home <span class="sr-only">(current)</span></a>
                </li>
                <li>
                    {% if not request.user.is_authenticated %}
                    <a href='{% url "login" %}'>Sign In</a>
                </li>
                <li >
                    <a href='{% url "register" %}'>Register</a>
                </li>
                   {% else %}
                <li>
                    <a href='{% url "logout" %}'>logout</a>
                    {% endif %}
                </li>
                <li class="nav-item text-white">
                    <a class="nav-link" href="#about">About</a>
                </li>
                <li><a href="#contact">CONTACT</a></li>-->
            </ul>
        </div>
    </div>
</nav>
<!-- end navigation -->

core/templates/core/transactions.html
{% extends 'core/base.html' %}



{% block content %}
{% include "core/nav.html" %}
{% include "core/messages.html" %}
<!-- start home -->
<section id="home">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-2 col-md-8">
        <h1 class="wow fadeIn" data-wow-offset="50" data-wow-delay="0.9s">welcome <span>{{ user.full_name }}</span></h1>
        <div>
          <br>
        {% block title %} {{ block.super }}{% endblock title %}


          <div class="row">

            <div class="col-xs-12 col-md-8 text-left">
              <h4><b>Account Name: </b>{{ user.full_name }}</h4>
              <h4><b>Date of Birth: </b>{{ user.birth_date }}</h4>
              <h4><b>Gender: </b>{{ user.gender }}</h4>
              <h4><b>Contact No: </b>{{ user.contact_no }}</h4>
              <h4><b>Email Address: </b>{{ user.email }}</h4>
              <h4><b>Address: </b>{{ user.Address }}</h4>
              <h4><b>Location: </b>{{ user.city }}, {{ user.country }}</h4>
              <h4><b>Occupation: </b>{{ user.occupation }}</h4>
            </div>
            <div class="col-xs-6 col-md-4 text-left">
              <h4><b>Account Created: </b>{{ user.date_joined|date:'d-m-Y' }}</h4>
              <h4><b>Account No: </b>{{ user.account_no }}</h4><br><br>

                <h4  class="card-body"><b>Account Balance: </b>{{ user.balance }} $</h4>
              <div class="well">
                <a class="btn btn-success" href="{% url 'transactions:deposit' %}">Deposit</a>
                <a class="btn btn-danger" href="{% url 'transactions:withdrawal' %}">Withdraw</a>
              </div>
            </div>

          </div>

          <hr>
        <a data-scroll href="{% url 'logout' %}" class="btn btn-default wow fadeInUp" data-wow-offset="50" data-wow-delay="0.6s">SIGN OUT</a>
      </div>
    </div>
  </div>
  </div>
</section>

<!-- end home -->

<!-- start Transaction/Deposit -->
<section id="about">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2 class="wow bounceIn" data-wow-offset="50" data-wow-delay="0.3s"> MY Quick <span>TRANSACTION DETAILS</span></h2>
      </div>
      <div class="col-md-4 col-sm-4 col-xs-12 wow fadeInLeft" data-wow-offset="50" data-wow-delay="0.6s">

        <h3>Deposit Details</h3>
        <table class="table table-hover table-bordered">
          <thead>
          <tr>
            <th>#</th>
            <th>Date / Time</th>
            <th>Details</th>
            <th>Amount ($)</th>
          </tr>
          </thead>
          <tbody>
          <tr>
            {% for obj in deposit %}
            <th scope="row">{{forloop.counter}}</th>
            <td>{{ obj.timestamp }}</td>
            <td>Deposit</td>
            <td>{{ obj.amount }}</td>
          </tr>
          {% endfor %}
          <tr>
            <th class="text-right" scope="row" colspan="3">Total</th>

            <td>{{ deposit_sum }}</td>
          </tr>

          </tbody>
        </table>
        <hr>
      </div>
    </div>
  </div>

</section>
<!-- end about -->

<!-- start team -->
<section id="team">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2 class="wow bounceIn" data-wow-offset="50" data-wow-delay="0.3s"><span>TYBANK</span> withdrawal(s)</h2>
      </div>
      <div class="col-md-3 col-sm-6 col-xs-12 wow fadeIn" data-wow-offset="50" data-wow-delay="1.3s">
        <h3>Withdrawal Details</h3>
        <table class="table table-hover table-bordered">
          <thead>
          <tr>
            <th>#</th>
            <th>Date / Time</th>
            <th>Details</th>
            <th>Amount ($)</th>
          </tr>
          </thead>
          <tbody>
          <tr>
            {% for obj in withdrawal %}
            <th scope="row">{{forloop.counter}}</th>
            <td>{{ obj.timestamp }}</td>
            <td>Withdrawal</td>
            <td>{{ obj.amount }}</td>
          </tr>
          {% endfor %}
          <tr>
            <th class="text-right" scope="row" colspan="3">Total</th>

            <td>{{ withdrawal_sum }}</td>
          </tr>

          </tbody>
        </table>
        <hr>

      </div>
    </div>
  </div>
</section>
<!-- start interest-->
<section id="service">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2 class="wow bounceIn" data-wow-offset="50" data-wow-delay="0.3s">TYBANK<span>PERIODIC</span> INTEREST</h2>
      </div>
      <div class="col-md-4 wow fadeIn" data-wow-offset="50" data-wow-delay="0.6s">
        <h3>Interest Details</h3>
        <table class="table table-hover table-bordered">
          <thead>
          <tr>
            <th>#</th>
            <th>Date / Time</th>
            <th>Details</th>
            <th>Amount ($)</th>
          </tr>
          </thead>
          <tbody>
          <tr>
            {% for obj in interest %}
            <th scope="row">{{forloop.counter}}</th>
            <td>{{ obj.timestamp }}</td>
            <td>Interest</td>
            <td>{{ obj.amount }}</td>
          </tr>
          {% endfor %}
          <tr>
            <th class="text-right" scope="row" colspan="3">Total</th>

            <td>{{ interest_sum }}</td>
          </tr>

          </tbody>
        </table>
        <hr>
      </div>
    </div>
  </div>

</section>
<!-- end servie -->

<hr>
<!-- start contact -->
{% include "core/contact.html" %}

{% endblock content %}